@host=http://localhost:8001/v1
@token= 12312231123

###
# @name createApp
POST {{host}}/platform/apps
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test-app",
  "introduction": "gh_9aaf412a5483,This is a test app",
  "picUrl": "https://example.com",
  "appId": "wx4c187683539f414d",
  "appSecret": "7fb747052d1f2055413fa6eb0fbe0944",
  "type": 1
}


###
# @name createApp2
POST {{host}}/platform/apps
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "蓝鲸小精灵",
  "introduction": "gh_28b76d98bc00,蓝鲸小精灵",
  "picUrl": "https://wx.qlogo.cn/mmopen/JCrT0AX1L5ibricJKIia0O48pibBicpJ9p2WfwQNmmicJRULyxo6XSJnBs11SgrCVVKQIDoR0iasNqhFLJibuQ8VCIrSPyRr19Jiau2os/64",
  "appId": "wx6898b2ec34091597",
  "appSecret": "da5a265561ed02903fdf7bc923026c2c",
  "type": 1
}

###
# @name captcha
GET {{host}}/auth/captcha
Content-Type: application/json


###
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin1",
  "captchaCode": "1234",
  "captchaKey": "123456123456"
}
