@host=http://localhost:8001/v1
@token= 12312231123

@pid=67fb56c0fbdc1c040cfeefb8

###
# @name CreateTag
POST {{host}}/apps/{{pid}}/tags?name=tag10001
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name QueryTag
GET {{host}}/apps/{{pid}}/tags
Authorization: Bearer {{token}}

###
# @name PullTags
POST {{host}}/apps/{{pid}}/tags/pull
Content-Type: application/json
Authorization: Bearer {{token}}
