SET NAMES = utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `wxbusiness` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `wxbusiness`;




SET FOREIGN_KEY_CHECKS = 1;
